<a href="https://colab.research.google.com/github/mingyi2013/2022-sbi-ci-workshop-pt2/blob/main/python_basic2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python basic 2024

# Reference

Python basic by alto Univ:

https://aaltoscicomp.github.io/python-for-scicomp/numpy/

# Env setting

## Link to Google drive

## Import packages

run following command:

In [ ]:
import os
!pwd

/root


In [ ]:
# this is a comment
print("hello")
print("welcomme to this tutorial")

hello
welcomme to this tutorial


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math


# Random data

In [ ]:
np.random.random(10)

array([0.45061556, 0.16373181, 0.4912972 , 0.21077436, 0.68396437,
       0.58785504, 0.98358801, 0.79900241, 0.24988086, 0.48746815])

Loof:     if... else ...

Loop if: ... else: ...

# Condition

## If/else

In [ ]:
x = 0
if x < 1:
  print("x is less than 1")
else:
  print("x is equal or larger than 1")

x is less than 1


## For i in range()

In [ ]:
times = int(3)
print(times)
for i in range(times):
    print("hello")

3
hello
hello
hello


# String


## find/replace

In [ ]:
s = "AGCCTTAAATTTCCC"
print(s)

AGCCTTAAATTTCCC


In [ ]:
# find string index
motif_ind = s.find("AAA")
print(motif_ind)

6


In [ ]:
# print string after motif to end
print(s[motif_ind:])

AAATTTCCC


In [ ]:
# print string between index and index + 3
print(s[motif_ind : motif_ind+3])

NameError: name 's' is not defined

In [ ]:
# replace above 4 letters by lower case
s2 = s[motif_ind : motif_ind+3].lower()
print(s2)

aaa


In [ ]:
# replace substring between [index: index+3] in s with s2:
s3 = s.replace(s[motif_ind : motif_ind+4], s2)
print(s3)

AGCCTTaaaTTCCC


## length by len()

In [ ]:
print(len(s))

15


In [ ]:
print("The length of motif is: \n", len(s2))

The length of motif is: 
 3


# numpy

## array

In [ ]:
import numpy as np
a = np.arange(10)
b = np.zeros(10)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = np.array([1,2,3])               # 1-dimensional array (rank 1)
b = np.array([[1,2,3],[4,5,6]])     # 2-dimensional array (rank 2)
print(b)
print(b.shape)                             # the shape (rows,columns)
print(b.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [ ]:
print(np.zeros((2, 3)))             # 2x3 array with all elements 0
print(np.ones((2,3)))               # 2x3 array with all elements 1

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.full((3,4), 8) # 3x4 array with all elements 8

\


In [ ]:
np.linspace(0,9,10)   # between 0-9, given 10 number in even space.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

\


In [ ]:
c = np.ones((3,3))
d = np.ones((3, 2), 'bool')  # 3x2 boolean array
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ True  True]
 [ True  True]
 [ True  True]]


## save npy file

In [ ]:
np.save('/my_data/test_file1.npy', a)           # save the array a to a .npy file
x = np.load('/my_data/test_file1.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#%cd
!pwd

/root
